import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Castle, ChevronRight, Plus, Save, Search, Trash2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useConnection } from '../lib/ConnectionContext';
import { useUnsavedGuard } from '../lib/useUnsavedGuard';
import { UnsavedChangesModal } from '../components/UnsavedChangesModal';
import './DungeonEditorPage.css';

const difficultyNames = { 0: 'Normal', 1: 'Heroic', 2: '10 Normal', 3: '25 Normal', 4: '10 Heroic', 5: '25 Heroic' };
const expansionNames = ['Classic', 'The Burning Crusade', 'Wrath of the Lich King'];
const blankRequirement = () => ({ requirement_type: 0, requirement_id: '', faction: 2, priority: 0, leader_only: false, requirement_note: '' });

export default function DungeonEditorPage() {
  const { readDungeonMaps, writeMapDifficultyCap, addMapDifficulty, deleteMapDifficulty, runAtomicWrite } = useConnection();
  const navigate = useNavigate();
  const [library, setLibrary] = useState({ maps: [], difficulties: [] });
  const [workspace, setWorkspace] = useState(null); const [selected, setSelected] = useState(null);
  const [search, setSearch] = useState(''); const [typeFilter, setTypeFilter] = useState('all'); const [expansion, setExpansion] = useState('all'); const [availability, setAvailability] = useState('all');
  const [tab, setTab] = useState('overview'); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState('');
  const [capDraft, setCapDraft] = useState({}); const [heroicCap, setHeroicCap] = useState(''); const [accessDraft, setAccessDraft] = useState(null);
  const dirty = Object.keys(capDraft).length > 0 || Boolean(accessDraft?._dirty); const guard = useUnsavedGuard(dirty);

  const loadLibrary = useCallback(async () => {
    setLoading(true); const result = await readDungeonMaps();
    if (result.success) { setLibrary(result.data); if (!selected && result.data.maps[0]) setSelected(result.data.maps[0]); }
    else setNotice(result.error || 'Could not read dungeon DBC data.'); setLoading(false);
  }, [readDungeonMaps, selected]);
  useEffect(() => { loadLibrary(); }, [loadLibrary]);
  const loadWorkspace = useCallback(async (map) => {
    if (!map) return; setWorkspace(null); setCapDraft({}); setAccessDraft(null);
    const result = await window.azeroth.dungeons.readWorkspace(map.id);
    if (result.success) setWorkspace(result.data); else setNotice(result.error || 'Could not load dungeon data.');
  }, []);
  useEffect(() => { loadWorkspace(selected); }, [selected, loadWorkspace]);
  const rows = useMemo(() => library.maps.filter(m => (!search || `${m.id} ${m.name}`.toLowerCase().includes(search.toLowerCase())) && (typeFilter === 'all' || String(m.type) === typeFilter) && (expansion === 'all' || String(m.expansion) === expansion) && (availability === 'all' || library.difficulties.some(d => d.mapId === m.id && String(d.difficulty) === availability))), [library.maps, library.difficulties, search, typeFilter, expansion, availability]);
  const difficulties = useMemo(() => library.difficulties.filter(d => d.mapId === selected?.id), [library.difficulties, selected]);
  const choose = (map) => { if (dirty && !window.confirm('Discard unsaved changes?')) return; setSelected(map); };
  const saveCaps = async () => {
    try { await runAtomicWrite(['MapDifficulty.dbc'], async () => {
      for (const d of difficulties) if (capDraft[d.id] !== undefined) { const r = await writeMapDifficultyCap({ id: d.id, maxPlayers: Number(capDraft[d.id]) }); if (!r.success) throw new Error(r.error); }
    }); setNotice('Player caps saved. Copy MapDifficulty.dbc to client and server, then restart worldserver.'); setCapDraft({}); await loadLibrary(); }
    catch (e) { setNotice(`Player-cap save failed: ${e.message}`); }
  };
  const addHeroicDifficulty = async () => {
    const cap = Number(heroicCap || selected.maxPlayers || 5);
    if (!Number.isInteger(cap) || cap < 1 || cap > 100) return setNotice('Heroic record was not added: enter a player cap from 1 to 100.');
    if (!window.confirm(`Add Heroic (difficulty 1) for ${selected.name} with a ${cap}-player cap? Normal-only creature and gameobject spawns will also be enabled for Heroic.`)) return;
    try { let changed = { creatures: 0, gameobjects: 0 }, portal = null; await runAtomicWrite(['MapDifficulty.dbc'], async () => { const r = await addMapDifficulty({ mapId: selected.id, difficulty: 1, maxPlayers: cap }); if (!r.success) throw new Error(r.error); const spawns = await window.azeroth.dungeons.setCustomHeroicCreatureSpawns({ mapId: selected.id, enabled: true }); if (!spawns.success) throw new Error(spawns.error); changed = spawns; portal = await window.azeroth.dungeons.setCustomHeroicPortal({ mapId: selected.id, enabled: true }); if (!portal.success) throw new Error(portal.error); }); setNotice(`Heroic record added; ${changed.creatures} creature and ${changed.gameobjects} gameobject spawns enabled for Heroic.${portal?.created ? ' RFC difficulty portal and skull overlay created.' : ''} Copy MapDifficulty.dbc to client and server, then restart worldserver.`); setHeroicCap(''); await loadLibrary(); }
    catch (e) { setNotice(`Could not add Heroic record: ${e.message}`); }
  };
  const deleteHeroicDifficulty = async () => {
    const heroic = difficulties.find(d => d.difficulty === 1 && d.id >= 10000);
    if (!heroic) return;
    if (!window.confirm(`Delete custom Heroic record #${heroic.id} for ${selected.name}? Shared creature and gameobject spawns (mask 3) will return to Normal-only (mask 1).`)) return;
    try { let changed = { creatures: 0, gameobjects: 0 }, portal = null; await runAtomicWrite(['MapDifficulty.dbc'], async () => { const r = await deleteMapDifficulty({ id: heroic.id }); if (!r.success) throw new Error(r.error); const spawns = await window.azeroth.dungeons.setCustomHeroicCreatureSpawns({ mapId: selected.id, enabled: false }); if (!spawns.success) throw new Error(spawns.error); changed = spawns; portal = await window.azeroth.dungeons.setCustomHeroicPortal({ mapId: selected.id, enabled: false }); if (!portal.success) throw new Error(portal.error); }); setNotice(`Custom Heroic record removed; ${changed.creatures} creature and ${changed.gameobjects} gameobject spawns restored to Normal-only.${portal?.removed ? ' RFC portal visuals removed.' : ''} Copy MapDifficulty.dbc to client and server, then restart worldserver.`); await loadLibrary(); }
    catch (e) { setNotice(`Could not delete custom Heroic record: ${e.message}`); }
  };
  const addRfcPortalVisual = async () => {
    const r = await window.azeroth.dungeons.setCustomHeroicPortal({ mapId: selected.id, enabled: true });
    setNotice(!r.success ? `Could not create RFC portal visual: ${r.error}` : r.repaired ? 'RFC portal displays repaired: blue Normal, purple Heroic portal and skull. Restart worldserver to load them.' : 'RFC blue Normal portal and purple Heroic portal plus skull created. Restart worldserver to load them.');
  };
  const removeRfcPortalVisual = async () => {
    if (!window.confirm('Remove only the Azeroth Editor RFC portal and skull visuals? The RFC Heroic record and entrance trigger remain intact.')) return;
    const r = await window.azeroth.dungeons.setCustomHeroicPortal({ mapId: selected.id, enabled: false });
    setNotice(!r.success ? `Could not remove RFC portal visual: ${r.error}` : r.removed ? 'RFC portal visuals removed; Heroic RFC remains enabled.' : 'No editor-created RFC portal visuals were found.');
  };
  const applyTenPlayerPreset = () => {
    const normal = difficulties.find(d => d.difficulty === 0);
    if (!normal) return setNotice('This map has no existing normal-dungeon difficulty record to change.');
    if (window.confirm(`Set ${selected.name} normal-dungeon cap from ${normal.maxPlayers} to 10? This only changes admission capacity; it does not create a raid mode.`)) setCapDraft(x => ({ ...x, [normal.id]: 10 }));
  };
  const editAccess = (template = null) => setAccessDraft(template ? { ...template, requirements: (workspace.access.requirements || []).filter(r => r.dungeon_access_id === template.id), _dirty: false } : { difficulty: 0, min_level: 0, max_level: 0, min_avg_item_level: 0, comment: '', requirements: [], _dirty: false });
  const saveAccess = async () => { const r = await window.azeroth.dungeons.saveAccess({ mapId: selected.id, template: accessDraft, requirements: accessDraft.requirements }); if (!r.success) return setNotice(`Access save failed: ${r.error}`); setNotice('Access rules saved. Use the supported worldserver reload for these custom tables if your core provides one.'); await loadWorkspace(selected); };
  const updateAccess = (key, value) => setAccessDraft(d => ({ ...d, [key]: value, _dirty: true }));
  const updateRequirement = (i, key, value) => setAccessDraft(d => ({ ...d, requirements: d.requirements.map((r, index) => index === i ? { ...r, [key]: value } : r), _dirty: true }));
  if (loading) return <div className="dungeon-page"><div className="loading-text">Loading Map.dbc…</div></div>;
  return <div className="dungeon-page">
    <header className="dungeon-header"><div><h1><Castle size={20} /> Dungeons</h1><p>Inspect existing instances, access rules and player-cap records.</p></div>{notice && <span className="dungeon-notice">{notice}</span>}</header>
    <div className="dungeon-workspace"><aside className="dungeon-library"><div className="dungeon-search"><Search size={14}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search map ID or name" /></div><div className="dungeon-filters"><select value={typeFilter} onChange={e => setTypeFilter(e.target.value)}><option value="all">All instances</option><option value="1">5-man</option><option value="2">Raid</option></select><select value={expansion} onChange={e => setExpansion(e.target.value)}><option value="all">All expansions</option>{expansionNames.map((n,i)=><option key={n} value={i}>{n}</option>)}</select><select value={availability} onChange={e => setAvailability(e.target.value)}><option value="all">Normal / Heroic</option><option value="0">Normal available</option><option value="1">Heroic available</option></select></div><div className="dungeon-results">{rows.map(m => <button key={m.id} onClick={() => choose(m)} className={selected?.id === m.id ? 'active' : ''}><strong>{m.name || `Map ${m.id}`}</strong><small>#{m.id} · {m.type === 2 ? 'Raid' : '5-man'} · {m.maxPlayers || '—'} players <ChevronRight size={12}/></small></button>)}</div></aside>
      <section className="dungeon-detail">{selected && <><div className="dungeon-title"><div><strong>{selected.name}</strong><span>Map #{selected.id} · {selected.type === 2 ? 'Raid' : 'Party dungeon'} · {expansionNames[selected.expansion] || `Expansion ${selected.expansion}`}</span></div></div><nav className="dungeon-tabs">{[['overview','Overview'],['difficulty','Difficulty & caps'],['access','Access'],['travel','Entrances & travel'],['content','Encounters & content'],['testing','Testing']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
        {!workspace ? <div className="loading-text">Loading instance data…</div> : <TabContent tab={tab} selected={selected} workspace={workspace} difficulties={difficulties} capDraft={capDraft} setCapDraft={setCapDraft} saveCaps={saveCaps} heroicCap={heroicCap} setHeroicCap={setHeroicCap} addHeroicDifficulty={addHeroicDifficulty} deleteHeroicDifficulty={deleteHeroicDifficulty} addRfcPortalVisual={addRfcPortalVisual} removeRfcPortalVisual={removeRfcPortalVisual} applyTenPlayerPreset={applyTenPlayerPreset} accessDraft={accessDraft} editAccess={editAccess} updateAccess={updateAccess} updateRequirement={updateRequirement} saveAccess={saveAccess} navigate={navigate} />}</>}</section>
    </div>{guard.blocked && <UnsavedChangesModal onConfirm={guard.confirm} onCancel={guard.cancel}/>}</div>;
}

function TabContent({ tab, selected, workspace, difficulties, capDraft, setCapDraft, saveCaps, heroicCap, setHeroicCap, addHeroicDifficulty, deleteHeroicDifficulty, addRfcPortalVisual, removeRfcPortalVisual, applyTenPlayerPreset, accessDraft, editAccess, updateAccess, updateRequirement, saveAccess, navigate }) {
  if (tab === 'overview') return <div className="dungeon-panel-grid"><Panel title="Instance overview"><Info label="Map ID" value={selected.id}/><Info label="Type" value={selected.type === 2 ? 'Raid' : 'Party dungeon (client-defined)'}/><Info label="Default players" value={selected.maxPlayers || 'Not set'}/><Info label="Parent map" value={workspace.instance?.parent ?? '—'}/><Info label="Instance script" value={workspace.instance?.script || 'None'}/><Info label="Allow mount" value={workspace.instance ? (workspace.instance.allowMount ? 'Yes' : 'No') : '—'}/></Panel><Callout>{workspace.instance ? 'The instance script is shown for reference only. Script editing belongs in the core/module workflow.' : 'No instance_template row exists for this map. The client still defines it as a party dungeon or raid.'}</Callout></div>;
  if (tab === 'difficulty') { const customHeroic = difficulties.find(d => d.difficulty === 1 && d.id >= 10000); return <div className="dungeon-panel-grid"><Panel title="Difficulty matrix"><table><thead><tr><th>Difficulty</th><th>Player cap</th><th>Reset</th><th>Record</th></tr></thead><tbody>{difficulties.map(d=><tr key={d.id}><td>{difficultyNames[d.difficulty] || `Difficulty ${d.difficulty}`}</td><td><input type="number" min="1" max="100" value={capDraft[d.id] ?? d.maxPlayers} onChange={e=>setCapDraft(x=>({...x,[d.id]:e.target.value}))}/></td><td>{d.raidDuration ? `${d.raidDuration / 86400} days` : 'Default'}</td><td>#{d.id}</td></tr>)}</tbody></table>{selected.type === 1 && !difficulties.some(d => d.difficulty === 1) && <div className="heroic-add"><label>Heroic player cap<input type="number" min="1" max="100" value={heroicCap || selected.maxPlayers || 5} onChange={e=>setHeroicCap(e.target.value)}/></label><button className="btn-ghost" onClick={addHeroicDifficulty}><Plus size={13}/> Add Heroic record</button></div>}{customHeroic && <button className="btn-ghost" onClick={deleteHeroicDifficulty}><Trash2 size={13}/> Delete custom Heroic #{customHeroic.id}</button>}{customHeroic && selected.id === 389 && <div className="heroic-add"><button className="btn-ghost" onClick={addRfcPortalVisual}><Plus size={13}/> Add / repair RFC portal displays</button><button className="btn-ghost" onClick={removeRfcPortalVisual}><Trash2 size={13}/> Remove RFC portal visuals</button></div>}{selected.type === 1 && <button className="btn-ghost" onClick={applyTenPlayerPreset}>Convert 5-man cap to 10</button>}<button className="btn-primary" disabled={!Object.keys(capDraft).length} onClick={saveCaps}><Save size={13}/> Save player caps</button></Panel><Callout>Adding a custom Heroic record enables Normal-only creature and gameobject spawns for Heroic. Deleting it restores only shared spawns; Heroic-only masks remain untouched.</Callout><Callout kind="warn">RFC portal displays are automatic: blue display 8243 on Normal, purple display 8196 plus skull display 8197 on Heroic.</Callout><Callout kind="warn">A Heroic record does not scale mobs, bosses, loot or scripts.</Callout></div>; }
  if (tab === 'access') return <div className="dungeon-panel-grid">{!workspace.access.available ? <Callout kind="warn">{workspace.access.error}</Callout> : <><Panel title="Entry requirements">{workspace.access.templates.map(t=><div className="access-row" key={t.id}><span>{difficultyNames[t.difficulty] || `Difficulty ${t.difficulty}`}</span><span>Lv {t.min_level || 0}{t.max_level ? `–${t.max_level}` : '+'} · iLvl {t.min_avg_item_level || 0}</span><button className="btn-ghost" onClick={()=>editAccess(t)}>Edit</button></div>)}<button className="btn-ghost" onClick={()=>editAccess()}><Plus size={13}/> Add access rule</button></Panel>{accessDraft && <Panel title="Edit access rule"><div className="dungeon-form"><label>Difficulty<input type="number" value={accessDraft.difficulty} onChange={e=>updateAccess('difficulty',e.target.value)}/></label><label>Min level<input type="number" value={accessDraft.min_level} onChange={e=>updateAccess('min_level',e.target.value)}/></label><label>Max level<input type="number" value={accessDraft.max_level} onChange={e=>updateAccess('max_level',e.target.value)}/></label><label>Min average item level<input type="number" value={accessDraft.min_avg_item_level} onChange={e=>updateAccess('min_avg_item_level',e.target.value)}/></label><label className="wide">Comment<input value={accessDraft.comment || ''} onChange={e=>updateAccess('comment',e.target.value)}/></label></div><h4>Requirements</h4>{accessDraft.requirements.map((r,i)=><div className="requirement-row" key={i}><select value={r.requirement_type} onChange={e=>updateRequirement(i,'requirement_type',e.target.value)}><option value="0">Achievement</option><option value="1">Quest</option><option value="2">Item</option></select><input placeholder="ID" value={r.requirement_id} onChange={e=>updateRequirement(i,'requirement_id',e.target.value)}/><select value={r.faction} onChange={e=>updateRequirement(i,'faction',e.target.value)}><option value="2">Both</option><option value="0">Alliance</option><option value="1">Horde</option></select><input placeholder="Failure note" value={r.requirement_note || ''} onChange={e=>updateRequirement(i,'requirement_note',e.target.value)}/><button onClick={()=>updateAccess('requirements',accessDraft.requirements.filter((_,x)=>x!==i))}><Trash2 size={13}/></button></div>)}<button className="btn-ghost" onClick={()=>updateAccess('requirements',[...accessDraft.requirements, blankRequirement()])}><Plus size={13}/> Requirement</button><button className="btn-primary" onClick={saveAccess}><Save size={13}/> Save access rule</button></Panel>}</>}</div>;
  if (tab === 'travel') return <Panel title="Entrances & travel"><table><thead><tr><th>Trigger</th><th>Target</th><th>Coordinates</th></tr></thead><tbody>{workspace.teleports.map(t=><tr key={t.id}><td>#{t.id}</td><td>Map #{t.target_map}</td><td>{[t.target_position_x,t.target_position_y,t.target_position_z,t.target_orientation].map(x=>Number(x || 0).toFixed(2)).join(', ')}</td></tr>)}</tbody></table><Callout>Teleport mutation is intentionally out of scope. Use the World Map or existing map tools for safe travel work.</Callout></Panel>;
  if (tab === 'content') return <div className="dungeon-panel-grid"><Panel title={`Creatures (${workspace.creatures.length})`}>{workspace.creatures.slice(0,100).map(c=><button className="content-link" key={c.guid} onClick={()=>navigate(`/creatures?select=${c.entry}`)}>{c.name || `Creature ${c.entry}`} <span>#{c.entry} · area {c.areaId || '—'} {c.difficulty_entry_1 ? '· difficulty variants' : ''}</span></button>)}</Panel><Panel title={`Gameobjects (${workspace.objects.length})`}>{workspace.objects.slice(0,100).map(g=><div className="content-link" key={g.guid}>{g.name || `GameObject ${g.entry}`} <span>#{g.entry} · area {g.areaId || '—'}</span></div>)}</Panel><Panel title="Quest links">{workspace.questPois.map(q=><button className="content-link" key={q.ID} onClick={()=>navigate(`/quests?select=${q.ID}`)}>{q.LogTitle} <span>#{q.ID}</span></button>)}</Panel><Callout>Checklist is intentionally local-editor metadata in the next phase; no server content is changed here.</Callout></div>;
  return <div className="dungeon-panel-grid"><Panel title="Operational guidance"><ul><li>SQL-only access changes may use a table-specific safe reload when your core/module supports it.</li><li>MapDifficulty DBC changes require client/server DBC synchronization and a worldserver restart.</li><li>Instance scripts, AI, new difficulty modes and scaling require core/module work.</li></ul></Panel></div>;
}
function Panel({ title, children }) { return <section className="dungeon-panel"><h3>{title}</h3><div>{children}</div></section>; }
function Info({ label, value }) { return <div className="info"><span>{label}</span><strong>{value}</strong></div>; }
function Callout({ children, kind='' }) { return <div className={`dungeon-callout ${kind}`}><AlertTriangle size={16}/><span>{children}</span></div>; }
