import { useEffect, useMemo, useState } from 'react';
import { X, UserRound } from 'lucide-react';
import CharM2Viewer from '../components/char/CharM2Viewer';
import { useConnection } from '../lib/ConnectionContext';

const RACES = [[1, 'Human'], [2, 'Orc'], [3, 'Dwarf'], [4, 'Night Elf'], [5, 'Undead'], [6, 'Tauren'], [7, 'Gnome'], [8, 'Troll'], [10, 'Blood Elf'], [11, 'Draenei']];
const RECTS = { armUpper:[0,0,128,64], armLower:[0,64,128,64], hands:[0,128,128,32], torsoUpper:[128,0,128,64], torsoLower:[128,64,128,32], legUpper:[128,96,128,64], legLower:[128,160,128,64], feet:[128,224,128,32] };
const hex = value => value ? [parseInt(value.slice(1, 3), 16), parseInt(value.slice(3, 5), 16), parseInt(value.slice(5, 7), 16)] : null;
const recolor = (data, profile) => { const mappings=(profile.colorMappings||[]).filter(row=>row.enabled&&hex(row.source)&&hex(row.target)); for(let i=0;i<data.length;i+=4){if(!data[i+3])continue;const source=[data[i],data[i+1],data[i+2]], match=mappings.map(row=>({row,d:Math.hypot(...source.map((value,index)=>value-hex(row.source)[index]))})).sort((a,b)=>a.d-b.d)[0];if(match&&match.d<=Number(match.row.tolerance||74)){const target=hex(match.row.target),light=(source[0]+source[1]+source[2])/765,scale=.42+light*.78;data[i]=Math.min(255,target[0]*scale);data[i+1]=Math.min(255,target[1]*scale);data[i+2]=Math.min(255,target[2]*scale);}}return data;};
const imageFromPng = png => new Promise((resolve, reject) => { const image = new Image(); image.onload=()=>resolve(image); image.onerror=reject; image.src=`data:image/png;base64,${png}`; });

export default function TextureWorkshopCharacterModal({ rows, profile, onClose }) {
  const { readCharSections, readItemDisplayInfos, readBlpTexture, worldmapMpqPath } = useConnection();
  const [race, setRace] = useState(1), [gender, setGender] = useState(0), [sections, setSections] = useState([]), [assets, setAssets] = useState({}), [skinRgba, setSkinRgba] = useState(null), [status, setStatus] = useState('Loading preview assets...');
  useEffect(() => { readCharSections().then(r => { if (r?.success) setSections(r.records || []); }); }, [readCharSections]);
  const ids = useMemo(() => [...new Set(rows.map(row => +row.displayid).filter(Boolean))], [rows]);
  useEffect(() => { let dead=false; if (!ids.length || !worldmapMpqPath) return; readItemDisplayInfos(worldmapMpqPath, ids, { race, gender }).then(r => { if (!dead && r?.success) setAssets(r.data || {}); }); return () => { dead=true; }; }, [ids, race, gender, readItemDisplayInfos, worldmapMpqPath]);
  const skin = useMemo(() => sections.find(r => +r.race === race && +r.sex === gender && +r.baseSection === 0 && +r.variationIndex === 0)?.tex1 || '', [sections, race, gender]);
  useEffect(() => { let dead=false; if (!skin || !worldmapMpqPath) return; const load=async()=>{ try { setStatus('Compositing exact recolor preview...'); const base=await readBlpTexture(worldmapMpqPath,skin); const image=await imageFromPng(base.png); const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0); for (const row of rows) for (const [region,path] of Object.entries((assets[row.displayid] || row.display)?.componentTexturePaths || {})) { const rect=RECTS[region]; if(!rect) continue; const r=await readBlpTexture(worldmapMpqPath,path); if(!r?.success) continue; const layer=await imageFromPng(r.png); const c=document.createElement('canvas');c.width=layer.width;c.height=layer.height;const cctx=c.getContext('2d');cctx.drawImage(layer,0,0);const pix=cctx.getImageData(0,0,c.width,c.height);cctx.putImageData(new ImageData(new Uint8ClampedArray(recolor(pix.data,profile)),c.width,c.height),0,0);ctx.drawImage(c,rect[0]*canvas.width/256,rect[1]*canvas.height/256,rect[2]*canvas.width/256,rect[3]*canvas.height/256); } const out=ctx.getImageData(0,0,canvas.width,canvas.height); if(!dead){setSkinRgba({data:new Uint8Array(out.data),width:canvas.width,height:canvas.height});setStatus('Live recolor preview. M2 attachments use the source texture until attachment recolor is enabled.');} } catch { if(!dead) setStatus('Some preview textures could not be composed.'); } }; load(); return()=>{dead=true;}; }, [skin, assets, rows, profile, readBlpTexture, worldmapMpqPath]);
  const attachedModels = useMemo(() => rows.flatMap(row => { const d=assets[row.displayid] || row.display, slot=+row.InventoryType;if(!d)return[];if(slot===1&&d.model1Path)return[{slot:`helm-${row.entry}`,attachmentId:11,modelPath:d.model1Path,texturePath:d.texture1Path||'',profile}];if(slot===3)return[{slot:`shoulder-left-${row.entry}`,attachmentId:6,modelPath:d.model1Path,texturePath:d.texture1Path||'',profile},{slot:`shoulder-right-${row.entry}`,attachmentId:5,modelPath:d.model2Path,texturePath:d.texture2Path||d.texture1Path||'',profile}].filter(m=>m.modelPath);if(slot===16&&d.model1Path)return[{slot:`cape-${row.entry}`,attachmentId:12,modelPath:d.model1Path,texturePath:d.texture1Path||'',profile}];return[];}),[rows,assets,profile]);
  return <div className="tw-modal-backdrop" onMouseDown={onClose}><section className="tw-character-modal" role="dialog" aria-modal="true" aria-label="Character equipment preview" onMouseDown={e=>e.stopPropagation()}><header><div><h2><UserRound size={17} /> Character equipment preview</h2><p>Live component recolor before export. Helm and shoulders use their real M2 attachment points.</p></div><button onClick={onClose}><X size={18}/></button></header><div className="tw-modal-controls"><label>Race<select value={race} onChange={e=>setRace(+e.target.value)}>{RACES.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Gender<select value={gender} onChange={e=>setGender(+e.target.value)}><option value={0}>Male</option><option value={1}>Female</option></select></label><small>{status}<br/>{attachedModels.length} resolved attachment model{attachedModels.length===1?'':'s'}.</small></div><div className="tw-modal-stage">{skinRgba?<CharM2Viewer race={race} gender={gender} skinBlp={skin} skinRgba={skinRgba} attachedModels={attachedModels} active={!!worldmapMpqPath}/>:<span>Loading character preview…</span>}</div></section></div>;
}
